### ISSUE TITLE
Blocks render size

### ISSUE THREAD

**Issue by Matthieu-BRANTHOME** [scratchblocks/scratchblocks#372]
Hi,

First thank you for this great project. 

How do I choose the size of the rendered blocks?

Thank you in advance for your help,

Matthieu

**Comment by Matthieu-BRANTHOME** [comment]
To be more precise, I need to downscale the blocks svg to 75%
But when I'm using:
```css
.scratchblocks > svg {    
    transform: scale(0.75);
}
```
the blocks are downscaled but the svg size (width and height) stay the same.

Any idea to "crop" the SVG after the scale transformation?

Thank you for your help,

Matthieu
